### PR TITLE
fix params

### PR DESCRIPTION
**Pull request by najathi**
I fixed params in react native woocommerce API. I've tested this code in my app, it works for me. Even it works with params. Please test and add main repo, Thank you

### CODE REVIEW

**Comment by najathi** [comment]
have you checked? I've changed one line of code, some formatted plugin makes double quotes, space, and extra. See this link, I have changed like this
https://github.com/JamesUgbanu/react-native-woocommerce-api/issues/13#issuecomment-657185846

**Comment by Dalper5** [comment]
Now I feel like I'm forced to pass a parameter, so get("products", { per_page: 100 }) works but get("products") throws a 401 error for some reason.

**Comment by JamesUgbanu** [comment]
> Now I feel like I'm forced to pass a parameter, so get("products", { per_page: 100 }) works but get("products") throws a 401 error for some reason.

This has been fixed in the latest update. Thank you for your observation @Dalper5

**Comment by Dalper5** [comment]
@JamesUgbanu - Thanks for the attempt, but it's back to being broken when passing the parameter:

WooAPI.get("products", { per_page: 100 }) results in woocommerce_rest_authentication_missing_parameter

Works ok without the parameter.

**Comment by najathi** [comment]
Nice

**Comment by JamesUgbanu** [comment]
Update to the recent version and try again. @Dalper5

**Pull request merged**
